customhost = "employee.ccw6ir13moog.us-east-1.rds.amazonaws.com"
customuser = "somebady"
custompass = "sucess125"
customdb = "employee"
custombucket = "somebadyaddemployee"
customregion = "us-east-1"
